### ISSUE TITLE
JDBC Support

### ISSUE THREAD

**Issue by writemevenkat** [joshdreagan/clustered-file-consumer#1]
Hello @joshdreagan. I'm looking for similar approach but using JDBC as a back-end idempotent repository.    Would like to design the solution which should be scalable and  re-used by multiple applications. Do you think using JDBC repository for the application which deals with 1500 files/minute and running 20 instances (Camel Springboot in Openshift POD ) will be a right choice ? Feedback would be appreciated. Thanks.

**Comment by joshdreagan** [comment]
Should work fine. As for performance, you'll have to test and see what you get (though, 1500/min is not a huge number). The only thing I can think of off the top of my head that you'll need to worry about is stale locks. Since the DB will likely be persistent, you could run into a case where an instance claims a file and adds it to the `inProgressRepository`, but crashes (ie, `kill -9`) before it finishes. That record will remain in the DB and will prevent any other instances (including the one that restarted) from picking up that file. One way to solve this would be to create a timeout/cleanup thread that scans for entries in the DB that are older than some threshold and removes them. Another way would be to implement your own version of `AbstractJdbcMessageIdRepository.java` that takes an "instance ID" into account. Then use Kubernetes StatefulSets and use the ordinal as the "instance ID". I'm sure there are other options as well, but you get the idea...
